// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6eV8K3u4IMn5lbII9xfRPDMQIeV2XHVc',
    appId: '1:365994525327:web:b430d161bfac74ad3ca6fa',
    messagingSenderId: '365994525327',
    projectId: 'iti-cors',
    authDomain: 'iti-cors.firebaseapp.com',
    storageBucket: 'iti-cors.appspot.com',
    measurementId: 'G-ECGZ8T5MMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT4wT9ImvJA3HXcnVGNMTEiRwxVMH0Gws',
    appId: '1:365994525327:android:6903886934bf774b3ca6fa',
    messagingSenderId: '365994525327',
    projectId: 'iti-cors',
    storageBucket: 'iti-cors.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1-NIIad-NigTsYUvUq0u30UVXqx21db0',
    appId: '1:365994525327:ios:f1ae737072b9b0f73ca6fa',
    messagingSenderId: '365994525327',
    projectId: 'iti-cors',
    storageBucket: 'iti-cors.appspot.com',
    iosClientId: '365994525327-pgk8msagchr52j3j8481durm33q3er0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1-NIIad-NigTsYUvUq0u30UVXqx21db0',
    appId: '1:365994525327:ios:a7e523045eaf68f33ca6fa',
    messagingSenderId: '365994525327',
    projectId: 'iti-cors',
    storageBucket: 'iti-cors.appspot.com',
    iosClientId: '365994525327-0ulln6jpm3tkadmlem9deb22h4a48nju.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
